name: format code with ruff

on:
  push:


jobs:
  code-format:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install ruff
      run: pip install ruff

    - name: Run ruff to format code
      run: |
        ruff check . --exit-zero
        ruff format .
        git add -u

    - name: Commit and push changes
      run: |
        git config --global user.name "HuntingBots"
        git config --global user.email "huntingbots.tg@gmail.com"
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit."
        else
          git commit -m "format: Auto-format code by ruff [skip actions]."
          git push origin ${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
